### ISSUE TITLE
Unable to run EssentialDotNetConfiguration project

### ISSUE THREAD

**Issue by imkheong** [IntelliTect/Articles#1]
Hey Mark

Thanks for the article on MSDN Magazine. Appreciated.

When trying to run the provided code, the code would fail complaining of a zero console window width.

[Configuration values are set here](https://www.dropbox.com/s/u10u3aw9x7ng58y/MSDN_screen1.png?dl=0)

[The values 'reset' to 0 when used](https://www.dropbox.com/s/smo4458gb4ajzy0/MSDN_screen2.png?dl=0)

Any idea what is the issue with that?

Thanks in advanced!

**Comment by ascott18** [comment]
Looks like the problem was that the properties on the POCO need to have setters in order for configuration properties to get loaded into them. It should be good to go now.

**Comment by MarkMichaelis** [comment]
Thanks Andrew!!  Wonder how this was ever working.  Stange!
